//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project19_TableStatusMomentary
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblTableDetails
    {
        public int DetailId { get; set; }
        public Nullable<int> TableId { get; set; }
        public string CustomerName { get; set; }
        public Nullable<bool> OrderStatus { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
        public string Note { get; set; }
    
        public virtual TblTables TblTables { get; set; }
    }
}
